FROM python:3

ENV PYTHONUNBUFFERED=1
# Set the working directory.

ADD webServer.py /
ADD BasicHealthReportGenerator.py /
ADD BhrReportOperations.py /

RUN pip install openpyxl
RUN pip install jira
RUN pip install flask
EXPOSE 5000
CMD [ "python", "./webServer.py" ]
