apiVersion: v1
kind: Service
metadata:
  name: test-webserver-service
spec:
  selector:
    app: webserver
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: ajitsrawat/webserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
