apiVersion: v1
kind: Service
metadata:
  name: test-webServer-service
spec:
  selector:
    app: test-webServer
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webServer
spec:
  selector:
    matchLabels:
      app: test-webServer
  replicas: 2
  template:
    metadata:
      labels:
        app: test-webServer
    spec:
      containers:
      - name: test-webServer
        image: test-webServer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000